### ISSUE TITLE
Decrypting old string issue

### ISSUE THREAD

**Issue by melloware** [alexscal/jasypt#1]
Hey I am using your patch so I can use SHA512 JDK 8 in Jasypt.  I found an issue though.

Using an old PBE like this...

   public static final StandardPBEStringEncryptor ENCRYPTOR = new StandardPBEStringEncryptor();
   static {
      ENCRYPTOR.setAlgorithm("PBEWithMD5AndDES");
      ENCRYPTOR.setPassword(PASSWORD);
   }

The current string is "kVTHVfAVDJ0vjqQimc3UsQ==" and it decrypts fine with Jasypt 1.9.2.  But the same with your patch fails here...

```java
if (ivGenerator.includePlainIVInEncryptionResults()) {

                // Extracting the IV
                iv = Arrays.copyOfRange(encryptedMessageKernel, 0, IVSizeBytes / 8);
                finalEncryptedMessage = Arrays.copyOfRange(encryptedMessageKernel, iv.length, encryptedMessageKernel.length);

                if (LOGGER.isDebugEnabled())
                        LOGGER.debug("Extracted IV: {}", Arrays.toString(iv));
            }
```

It I reencrypt my string using your library the string is a lot longer than it was before.    Any help on why the old conversion is now broken?

**Comment by melloware** [comment]
I ended up writing a NoOpIvGenerator where you want to encrypt or decrypt without IV.  Attached are the two classes touched to make it work like this...

```java
public static final StandardPBEStringEncryptor WEAK_ENCRYPTOR = new StandardPBEStringEncryptor();
   static {
      WEAK_ENCRYPTOR.setAlgorithm(WEAK_ALGORITHM);
      WEAK_ENCRYPTOR.setPassword(WEAK_PASSWORD);
      WEAK_ENCRYPTOR.setIVGenerator(new NoOpIVGenerator(null));
   }
```

Attachment: 
[noop-ivgenerator.zip](https://github.com/alexscal/jasypt/files/2207730/noop-ivgenerator.zip)

**Comment by alexscal** [comment]
Hi melloware, 

thank you! 

I will look into it.

Feel free to open a pull request!

Regards,
Alex

**Comment by melloware** [comment]
OK will do!  wasn't sure if you would accept it or not. I will submit it tomorrow.

**Comment by melloware** [comment]
PR Submitted.
